export { BrowserManager } from "./manager.js";
export {
  resolveLocalBinary,
  isCamoufoxInstalled,
  prefetchCamoufox,
  isCamoufoxPrefetching,
} from "./binaries.js";
export type { LocalBrowserKind } from "./binaries.js";
export {
  createBrowserProvider,
  PROVIDER_NAMES,
  LocalChromeProvider,
  BrowserbaseProvider,
  BrowserUseProvider,
  FirecrawlProvider,
} from "./providers/index.js";
export type {
  AcquiredBrowser,
  BrowserProvider,
  ProviderName,
} from "./providers/index.js";
export type {
  BrowserConfig,
  TabId,
  TabInfo,
  ConsoleEntry,
  NavigateParams,
  NavigateResult,
  SnapshotParams,
  SnapshotResult,
  ClickParams,
  TypeParams,
  PressKeyParams,
  ScreenshotParams,
  ScreenshotResult,
  WaitForParams,
  EvaluateParams,
  EvaluateResult,
  ConsoleMessagesParams,
  ConsoleMessagesResult,
  HoverParams,
  DragParams,
  SelectOptionParams,
  SelectOptionResult,
  FillFormField,
  FillFormParams,
  FillFormResult,
  FileUploadParams,
  HandleDialogParams,
  DialogResult,
  ResizeParams,
  ResizeResult,
  SaveAsPdfParams,
  PdfResult,
  ClickCoordsParams,
  NavHistoryResult,
  ActionResult,
} from "./types.js";
