import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { runCmd } from "./common.js";
import type { InstallOpts, PlatformLifecycle, ServiceStatus } from "./types.js";

const LABEL = "com.openacme";

function plistPath(): string {
  return path.join(os.homedir(), "Library", "LaunchAgents", `${LABEL}.plist`);
}

function uid(): number {
  return process.getuid?.() ?? 0;
}

function serviceTarget(): string {
  return `gui/${uid()}/${LABEL}`;
}

/**
 * Path to the wrapper shell script we install at <dataDir>/bin/openacme.
 * Settings → Login Items reads the executable's filename, so without this
 * indirection the OS UI would display "node" — confusing and ugly. The
 * wrapper just execs node with the right args so launchd / Activity
 * Monitor / Settings all surface "openacme" as the program name.
 */
function wrapperPath(dataDir: string): string {
  return path.join(dataDir, "bin", "openacme");
}

function escapeShellSingle(s: string): string {
  // 'foo' style — wrap in single quotes, escape any embedded ones.
  return `'${s.replaceAll("'", "'\\''")}'`;
}

function renderWrapper(opts: InstallOpts): string {
  // exec keeps a single PID for launchd to track; -- guards against weirdly
  // named binPaths starting with -. The "$@" tail forwards launchd's args
  // (we don't pass any beyond __serve, but it's the safe default).
  return `#!/bin/sh
# Auto-generated by \`openacme start\`. Do not edit; this file is rewritten
# whenever the daemon's bind/data dir/node path changes.
exec ${escapeShellSingle(opts.nodePath)} ${escapeShellSingle(opts.binPath)} __serve "$@"
`;
}

function escapeXml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function renderPlist(opts: InstallOpts, wrapper: string): string {
  // Optional env vars: forward through when set on the caller's environment
  // so the daemon picks them up on next launchd boot. Telemetry is the
  // current opt-in; add more here if other dev/diag flags need to survive
  // a `pnpm agent restart`. Without this passthrough, a manual plist edit
  // would be overwritten on every restart.
  const passthrough: Array<[string, string | undefined]> = [
    ["OPENACME_TELEMETRY", process.env["OPENACME_TELEMETRY"]],
    ["OPENACME_DEBUG", process.env["OPENACME_DEBUG"]],
    ["OPENACME_LOG_FILE", process.env["OPENACME_LOG_FILE"]],
  ];
  const extraEnv = passthrough
    .filter(([, v]) => typeof v === "string" && v.length > 0)
    .map(([k, v]) => `    <key>${k}</key><string>${escapeXml(v!)}</string>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(wrapper)}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>OPENACME_DATA_DIR</key><string>${escapeXml(opts.dataDir)}</string>
    <key>PATH</key><string>/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin</string>${extraEnv ? "\n" + extraEnv : ""}
  </dict>
  <key>WorkingDirectory</key><string>${escapeXml(opts.dataDir)}</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key><false/>
    <key>Crashed</key><true/>
  </dict>
  <key>ThrottleInterval</key><integer>5</integer>
  <key>StandardOutPath</key><string>${escapeXml(opts.logPath)}</string>
  <key>StandardErrorPath</key><string>${escapeXml(opts.logPath)}</string>
</dict>
</plist>
`;
}

function writeWrapper(opts: InstallOpts): string {
  const target = wrapperPath(opts.dataDir);
  const dir = path.dirname(target);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(target, renderWrapper(opts), { mode: 0o700 });
  // chmod again post-write to defeat umask if it stripped exec bits.
  try { fs.chmodSync(target, 0o700); } catch { /* best-effort */ }
  return target;
}

export const darwinLifecycle: PlatformLifecycle = {
  kind: "launchd",

  unitPath(): string {
    return plistPath();
  },

  async installUnit(opts: InstallOpts): Promise<{ wrote: boolean; path: string }> {
    const target = plistPath();
    // Always rewrite the wrapper — it's cheap and safe, and the Plist's
    // expected contents reference the wrapper's absolute path.
    const wrapper = writeWrapper(opts);
    const next = renderPlist(opts, wrapper);
    const existing = fs.existsSync(target) ? fs.readFileSync(target, "utf-8") : null;
    if (existing === next) return { wrote: false, path: target };
    const dir = path.dirname(target);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    // Plist stays world-readable (default) — no secrets in it. EnvironmentVariables
    // only carries OPENACME_DATA_DIR and PATH, both non-sensitive.
    fs.writeFileSync(target, next, { encoding: "utf-8" });
    // If the unit was loaded with the previous content, kick it so launchd
    // re-reads the file. Ignore failures — the unit may simply not be loaded.
    if (existing) {
      await runCmd("launchctl", ["bootout", serviceTarget()]).catch(() => undefined);
    }
    return { wrote: true, path: target };
  },

  async uninstallUnit(): Promise<void> {
    await runCmd("launchctl", ["bootout", serviceTarget()]).catch(() => undefined);
    try { fs.unlinkSync(plistPath()); } catch { /* ignore */ }
  },

  async startService(): Promise<void> {
    const target = plistPath();
    if (!fs.existsSync(target)) {
      throw new Error(`launchd unit missing: ${target}`);
    }
    // bootstrap loads the unit and starts it (RunAtLoad=true). If it's
    // already loaded, bootstrap fails — kickstart instead to nudge it.
    const boot = await runCmd("launchctl", ["bootstrap", `gui/${uid()}`, target]);
    if (boot.code === 0) return;
    // 17 = "Service already loaded" — fall through to kickstart.
    const kick = await runCmd("launchctl", ["kickstart", "-k", serviceTarget()]);
    if (kick.code !== 0) {
      throw new Error(
        `launchctl bootstrap and kickstart both failed.\nbootstrap: ${boot.stderr.trim()}\nkickstart: ${kick.stderr.trim()}`
      );
    }
  },

  async stopService(): Promise<void> {
    // bootout takes the unit out of launchd's view, which honors our
    // KeepAlive dict's "SuccessfulExit=false" — the daemon stays stopped.
    const out = await runCmd("launchctl", ["bootout", serviceTarget()]);
    // Non-zero is OK when the unit isn't loaded.
    void out;
  },

  async status(): Promise<ServiceStatus> {
    const installed = fs.existsSync(plistPath());
    if (!installed) return { running: false, unitInstalled: false };
    const res = await runCmd("launchctl", ["print", serviceTarget()]);
    if (res.code !== 0) return { running: false, unitInstalled: true };
    const pidMatch = res.stdout.match(/^\s*pid\s*=\s*(\d+)\s*$/m);
    // launchctl emits multi-word states like "spawn scheduled", "waiting" —
    // capture the rest of the line, not just \w+.
    const stateMatch = res.stdout.match(/^\s*state\s*=\s*(.+?)\s*$/m);
    const pid = pidMatch ? Number.parseInt(pidMatch[1]!, 10) : undefined;
    const state = stateMatch?.[1]?.trim();
    // "running" alone means the launchd-managed child is alive. Any pid > 0
    // also implies a live child. Anything else (spawn scheduled, waiting,
    // not running) → not running.
    const running = state === "running" || (pid !== undefined && pid > 0);
    return { running, pid, unitInstalled: true };
  },
};
